\c stackreport;

DROP TABLE IF EXISTS USERS CASCADE;

DROP TABLE IF EXISTS FUND CASCADE;

DROP TABLE IF EXISTS PREDICTION CASCADE;

DROP TABLE IF EXISTS PREDICTION_META CASCADE;

DROP TABLE IF EXISTS FOLLOW CASCADE;

DROP TABLE IF EXISTS TIER CASCADE;

DROP VIEW IF EXISTS PUBLIC_USERS;